# Generated by Django 5.2.8 on 2026-02-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoundCloudToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("refresh_token", models.CharField(max_length=50)),
                ("expires_in", models.DateTimeField()),
                ("access_token", models.CharField(max_length=50)),
            ],
        ),
    ]
