# Generated by Django 5.2.8 on 2026-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soundcloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soundcloudtoken",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="soundcloudtoken",
            name="refresh_token",
            field=models.TextField(),
        ),
    ]
