# Generated by Django 5.2.8 on 2026-02-13 20:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=api.models.generate_code, max_length=6, unique=True
                    ),
                ),
                ("host", models.CharField(max_length=50, unique=True)),
                ("guest_can_pause", models.BooleanField(default=False)),
                ("votes_to_skip", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_playing", models.BooleanField(default=False)),
                ("current_track_id", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
