# Generated by Django 5.2.8 on 2026-01-22 09:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="can_pause",
            new_name="guest_can_pause",
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_code, max_length=6, unique=True
            ),
        ),
    ]
