# Generated by Django 5.2.8 on 2026-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_can_pause_room_guest_can_pause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
