# Generated by Django 5.2.8 on 2026-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_room_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_track_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
